version: "3.7"
services:
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - "3002:5432"
